spring:
  application:
    name: tarefas-api
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/tarefas}
    username: ${POSTGRES_USUARIO:admin}
    password: ${POSTGRES_SENHA:admin}
    driverClassName: org.postgresql.Driver